version: '3.7'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
    networks:
      artemis:
        ipv4_address: 172.28.0.3

  heimdall:
    container_name: heimdall
    restart: unless-stopped
    image: linuxserver/heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/heimdall:/config
    ports:
      - 80:80
      - 443:443

  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
    networks:
      artemis:
        ipv4_address: 172.28.0.2

  radarr:
    image: 'linuxserver/radarr'
    container_name: 'radarr'
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - '${USERDIR}/docker/shared/downloads:/downloads:ro'
      - /mnt/Movies/Movies:/movies
      - '/etc/localtime:/etc/localtime:ro'
      - ${USERDIR}/docker/shared:/shared
    ports:
      - '7878:7878'
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      artemis:
        ipv4_address: 172.28.0.4

  sonarr:
    image: 'linuxserver/sonarr'
    container_name: 'sonarr'
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - '${USERDIR}/docker/shared/downloads:/downloads:ro'
      - /mnt/Television/Television:/tv
      - '/etc/localtime:/etc/localtime:ro'
      - ${USERDIR}/docker/shared:/shared
    ports:
      - '8989:8989'
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      artemis:
        ipv4_address: 172.28.0.5

  jackett:
    image: 'linuxserver/jackett'
    container_name: 'jackett'
    volumes:
      - ${USERDIR}/docker/jackett:/config
      - '/etc/localtime:/etc/localtime:ro'
      - ${USERDIR}/docker/shared:/shared
    ports:
      - '9117:9117'
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      artemis:
        ipv4_address: 172.28.0.8

  transmission:
    image: 'linuxserver/transmission'
    container_name: 'transmission'
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/transmission:/config
      - /mnt/Movies/Movies:/Movies
      - /mnt/Television/Television:/Television
      - '${USERDIR}/docker/shared/downloads:/downloads:rw'
    ports:
      - 9091:9091
      - 51413:51413
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      artemis:
        ipv4_address: 172.28.0.7

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/bazarr:/config
      - /mnt/Movies/Movies:/movies
      - /mnt/Television/Television:/tv
    ports:
      - 6767:6767
    networks:
      artemis:
        ipv4_address: 172.28.0.10
    restart: unless-stopped

networks:
  artemis:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
